CREATE SEQUENCE INDEX_CRITERIA_SEQ INCREMENT BY 1 START WITH 1000;
CREATE SEQUENCE DOMAIN_SEQ INCREMENT BY 1 START WITH 0;
CREATE SEQUENCE USER_SEQ INCREMENT BY 1 START WITH 1000;
CREATE SEQUENCE ROLE_SEQ INCREMENT BY 1 START WITH 1000;
CREATE SEQUENCE CONTENT_SEQ INCREMENT BY 1 START WITH 1000;
CREATE SEQUENCE CONTENT_COMMENT_SEQ INCREMENT BY 1 START WITH 1000;