CREATE TABLE CONTENT_INDEX_CRITERIA (
                CONTENT_REF INT(10) NOT NULL,
                INDEX_CRITERIA_REF INT(10) NOT NULL,
                PRIMARY KEY (CONTENT_REF, INDEX_CRITERIA_REF)
);