ALTER TABLE CONTENT ADD CONSTRAINT user_content_fk
FOREIGN KEY (AUTHOR_REF)
REFERENCES USER (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE CONTENT ADD CONSTRAINT content_ancestor_content_fk
FOREIGN KEY (CONTENT_ANCESTOR_REF)
REFERENCES CONTENT (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;
