INSERT INTO CONTENT_STATUS (ID, LABEL) VALUES (0, 'DRAFT');
INSERT INTO CONTENT_STATUS (ID, LABEL) VALUES (1, 'TO_BE_VALIDATED');
INSERT INTO CONTENT_STATUS (ID, LABEL) VALUES (2, 'VALIDATED');
INSERT INTO CONTENT_STATUS (ID, LABEL) VALUES (3, 'REJECTED');
INSERT INTO CONTENT_STATUS (ID, LABEL) VALUES (4, 'TO_BE_DELETED');
INSERT INTO CONTENT_STATUS (ID, LABEL) VALUES (5, 'DELETED');
INSERT INTO CONTENT_STATUS (ID, LABEL) VALUES (6, 'ARCHIVED');