ALTER TABLE CONTENT_DOMAIN ADD CONSTRAINT cd_content_fk
FOREIGN KEY (CONTENT_REF)
REFERENCES CONTENT (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE CONTENT_DOMAIN ADD CONSTRAINT cd_domain_fk
FOREIGN KEY (DOMAIN_REF)
REFERENCES DOMAIN (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;