INSERT INTO ROLE (ID, ROLENAME) VALUES (ROLE_SEQ.nextVal, 'student');
INSERT INTO ROLE (ID, ROLENAME) VALUES (ROLE_SEQ.nextVal, 'teacher');
INSERT INTO ROLE (ID, ROLENAME) VALUES (ROLE_SEQ.nextVal, 'administrator');
COMMIT;